### ISSUE TITLE
make and loading plugin always ask to fill out profile

### ISSUE THREAD

**Issue by tchajed** [uwplse/coq-change-analytics#34]
I'm always being asked to fill out a profile every time when running `./make` and when loading the plugin (via `coqtop` I can see this happening, Proof General just hangs). I'm installing the plugin into user-contrib in a local Coq install pointed to Coq master (coq/coq@67c7c565361055bf57a75646b940e124e068ef24).

**Comment by tlringer** [comment]
Thanks for testing this out before Beta actually started. What operating system are you on? Can you check whether you have a `.analytics_profile` in your home directory?

**Comment by tlringer** [comment]
Actually, I see the bug, so do not bother answering my question. I'll deploy the fix when I get home.

**Comment by tlringer** [comment]
I have deployed what should be a fix; please try again. It should ask you one more time (it wasn't saving your answers before) and then never again after that. Please let me know if it works for you.

**Comment by tchajed** [comment]
I think I have a bug in my stored profile; I'm now getting this error when I compile:

```
COQC theories/Analytics.v
File "./theories/Analytics.v", line 1, characters 0-30:
Error:
Anomaly
"Uncaught exception (Failure
  "Sexplib.Sexp.of_string: got multiple S-expressions where only one was expected.")."
```

and this error when I try to reset my profile:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

I was able to build and store a profile with a local server (after changing the `server_uri` in analytical.ml).

**Comment by tlringer** [comment]
Interesting, I'll take a look at the server output.

**Comment by tlringer** [comment]
Does it work if you remove your ~/.analytics_profile and start from scratch? I think the server got into a bad state somehow. I will look into this more.

Sorry for the inconvenience.

**Comment by tlringer** [comment]
I see your errors on the server. I'll investigate more.

**Comment by tchajed** [comment]
Sounds good.

It's not inconvenient at all! I like the idea of this project a lot and basically have infinite patience to beta test, especially since you're doing all the debugging.

**Comment by tlringer** [comment]
This is going to sound weird, but can you remove your ~/.analytics_profile again and try once more? users.txt is empty now, and I think maybe before it didn't exist and that distinction might cause a bug.

**Comment by tlringer** [comment]
Actually, hold on a bit more. I'm fine debugging right now. I'll let you know when I'm ready for more input.

**Comment by tlringer** [comment]
Everything is fixed now. Tested remotely. Please remove your ~/.analytics_profile and try again.

The issue was a deployment issue. The server didn't have the fix that I tried to make yesterday, for some reason!

**Comment by tchajed** [comment]
Seems to work, thanks!
